# Generated by Django 4.2.6 on 2023-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_category_options_alter_info_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='photo',
            field=models.ImageField(null=True, upload_to='photoes/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
